Diego
scesi/scesi-website pull request #10
Opened 2024-02-06 19:43 UTC by diegopl653

Add: Background animation from home page, and global navbar

2024-02-06 20:23 UTC, devferx requested changes
👏  Me saco el sombrero ante las animaciones, pero aún hay un par de cosas que refactorizar, estas muy cerca de terminar 😄 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2o5NHV4c3I3cW96eW1tbnJncmh6MzZ5cmpwcW94dWw3bDBzMXRnZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WO5Q7FsxJN2pjYc424/giphy.gif)

2024-02-06 20:23 UTC, devferx commented on src/components/HomeScesi.astro
Sugerencia: Pon los svg del logo en un componente aparte, podría estar ubicado en `components/icons/logo.astro` y lo llamarías <Logo />

Este componente solamente tendria el svg, y si es posible podrías hacer que envíes propiedades de Iconos HTML al componente ejemp `<Logo width="100px" />`

2024-02-06 20:23 UTC, devferx commented on src/components/HomeScesi.astro
> +    <img src="../../public/Trazado_Triangle_1372.svg" style="--i:9;" />
Astro esta enviando un warning que dice que cambies la ruta del archivo 
de: `../../public/Trazado_Triangle_1372.svg`
a: `/Trazado_Triangle_1372.svg`
Astro automáticamente busca en la ruta public

Recomendación: Ayudate del multicursor de VS Code para hacer este cambio si no sera muy doloroso xd

Mi recomendación es que tengas una subcarpeta `public/icons`

2024-02-06 20:23 UTC, devferx commented on src/components/HomeScesi.astro
> +<script>
Remueve las partes de codigo que no estas usando

2024-02-06 20:23 UTC, devferx commented on src/layouts/Layout.astro
> +    <link
Trae los cambios de la rama main

2024-02-12 15:03 UTC, diegopl653 commented on src/components/HomeScesi.astro
Corregido en el ultimo commit

2024-02-12 15:04 UTC, diegodev-01 commented on src/layouts/Layout.astro
> +    <link
Corregido en el ultimo commit

2024-02-12 15:04 UTC, diegopl653 commented on src/components/HomeScesi.astro
> +<script>
Corregido en el ultimo commit

2024-02-12 15:04 UTC, diegopl653 commented on src/components/HomeScesi.astro
> +    <img src="../../public/Trazado_Triangle_1372.svg" style="--i:9;" />
Corregido en el ultimo commit

2024-02-13 01:54 UTC, merged