Feature/contact us
scesi/scesi-website pull request #8
Opened 2024-02-06 01:17 UTC by MircoPilcoPeralta

2024-02-06 11:53 UTC, devferx requested changes
Estas muy cerca de acabar 😄 Realiza los cambios mencionados

2024-02-06 11:53 UTC, devferx commented on src/components/ContactCard.astro
Recomendación: Trata de manejar la cantidad menor de tamaños exactos

Una solución a la tarjeta podría ser está donde:
- El máximo tamaño es 300px de ancho
- La imagen ocupa todo el ancho de la tarjeta y mantiene su aspecto de cuadrado con `aspect-ratio` y `object-fit`
- El contenido de la tarjeta está en una caja donde podrías agrupar y si es necesario agregar un padding
```html
<div class="flex max-w-[300px] flex-col gap-3 py-0 text-center">
  <img class="aspect-square w-[100%] object-cover" src={imageUrl} alt={title} />
  <div class="...">
      <p class="text-2xl font-semibold">{title}</p>
      <slot class="text-base font-normal" name="content" />
      <a
        class="m-auto mt-3 block h-[52px] rounded-md bg-red-600 px-[18px] py-3 text-lg font-bold text-white"
        href={redirectTo}
      >
        {textButton}
      </a>
  </div>
</div>
```

2024-02-06 11:53 UTC, devferx commented on src/components/ContactWithUs.astro
> +    <div class="px-24 flex flex-col items-center lg:flex-row lg:justify-evenly">
Quizás con la siguiente clase quede un poco mejor alineado dado los cambios de la tarjeta, **requiere unos ajustes**
`class="flex flex-col items-center gap-6 lg:flex-row lg:items-start lg:justify-evenly lg:px-24"`

2024-02-06 11:53 UTC, devferx commented on src/layouts/Layout.astro
> +    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
Trae los últimos cambios de main para no tener problemas al momento de hacer merge

2024-02-06 11:53 UTC, devferx commented on src/layouts/Layout.astro
> +  <body class="font-Poppins">
Los textos deben estar con la clase `font-poppins` como tal agregar a todo el sitio la fuente no lo recomendaría en este proyecto

2024-02-07 17:17 UTC, devferx requested changes
Tareas pendientes:
- Trae los últimos cambios antes de hacer el pull request
- utiliza el comando npm run format antes de hacer push a la rama o realizar un pull request

2024-02-07 17:17 UTC, devferx commented on src/layouts/Layout.astro
No olvides borrar las lineas de google fonts
```
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
```

2024-02-07 17:17 UTC, devferx commented on src/pages/index.astro
> +  <button
Puedes borrar el boton xd

2024-02-15 20:44 UTC, devferx commented on src/layouts/Layout.astro
> +  <body class="font-Poppins">
Esta linea será removida

2024-02-15 20:52 UTC, MircoPilcoPeralta commented on src/layouts/Layout.astro
> +  <body class="font-Poppins">
Listo

2024-02-15 21:06 UTC, merged

2024-02-15 21:06 UTC, devferx commented
✅  Approved