Feature/about us
scesi/scesi-website pull request #9
Opened 2024-02-06 05:58 UTC by IVANCCAMA

2024-02-06 12:02 UTC, devferx requested changes

2024-02-06 12:02 UTC, devferx commented on src/components/about-us.astro
> +      <p class="text-center text-2xl font-semibold">Acerca de Nosotros</p>
El titulo debe ser tener un tamaño de `32px`

2024-02-06 12:02 UTC, devferx commented on src/components/about-us.astro
Recomendación: Puedes crear un componente `AboutUsCard` para evitar la duplicidad de código y cumplir el principio DRY (Don't repeat Yourself)

2024-02-08 15:08 UTC, devferx requested changes
Cada vez más cerca 💪

2024-02-08 15:08 UTC, devferx commented on src/pages/index.astro
> +import AboutUs from '../components/AboutUsCard.astro';
El nombre correcto del archivo seria `AboutUs.astro`

2024-02-08 15:08 UTC, devferx commented on src/components/AboutUsCard.astro
> +      <div class="contenido flex flex-col-reverse justify-center md:flex-row">
Toda esta parte de las tarjetas deberia ser un componente
```jsx
      <div class="contenido flex flex-col-reverse justify-center md:flex-row">
        <p class="m-auto text-center font-sans md:w-3/5 md:p-4 mr-0 md:mr-10">
          Organizar y coordinar la asistencia de estudiantes de nuestra Facultad
          y Sociedad a eventos de carácter científico a nivel local, nacional e
          internacional.
        </p>
        <Image
          class="h-48 w-full rounded-lg object-cover md:h-auto md:w-2/5"
          src={image1}
          alt="Eventos de carácter científico a nivel local"
        />
      </div>
```

Lo llamaria de esta manera
```jsx
<AboutUsCard
        img={image1}
        alt="Eventos de carácter científico a nivel local"
        content="Organizar y coordinar la asistencia de estudiantes de nuestra Facultad y Sociedad a eventos de carácter científico a nivel local, nacional e internacional."
        isPictureRight={false}
      />
```

Nótese que isPictureRight es una propiedad booleana, lo que deberías hacer es manejar la clase `flex-col-reverse` o `flex-col` como si fuera dinamica

```jsx
<div class="contenido flex flex-col-reverse justify-center md:flex-row">
```
Para ello manejaras class:list dentro del componente de la tarjeta, te dejo la documentación para que te guíes
https://docs.astro.build/en/guides/styling/#combining-classes-with-classlist

2024-02-10 03:39 UTC, IVANCCAMA commented on src/components/AboutUsCard.astro
> +      <div class="contenido flex flex-col-reverse justify-center md:flex-row">
El componente `AboutUs `debe de estar en `index.astro`?

2024-02-11 21:05 UTC, devferx commented on src/components/AboutUsCard.astro
> +      <div class="contenido flex flex-col-reverse justify-center md:flex-row">
Correcto

2024-02-12 13:04 UTC, merged